### ISSUE TITLE
permitir filtrar por oucs

### ISSUE THREAD

**Issue by yubathom** [SPURB/outorga-backend#11]
permitir que `/fila` seja filtrado por `OperacaoUrbana` ou por múltiplos `Setores`

**Comment by hsolucas** [comment]
Foi incluído um filtro "IdOpUrbanaSrc". Favor validar.

https://servicos.spurbanismo.sp.gov.br/cepacs/api/fila?idopurbanasrc=2

**Comment by yubathom** [comment]
perfeito @hsolucas

**Comment by yubathom** [comment]
@m-dantas

**Comment by yubathom** [comment]
Fala @hsolucas, esta funcionalidade não está espelhada na instância da Intranet:
A endpoint abaixo está vindo com toda a fila
http://spurbsp198/cepacs/api/fila?idopurbanasrc=1

A resposta esperada deveria ser igual à instância pública, um array vazio:
https://servicos.spurbanismo.sp.gov.br/cepacs/api/fila?idopurbanasrc=1

**Comment by yubathom** [comment]
Resolvido e testado
