### ISSUE TITLE
query filter de /fila?IdGeo não funciona

### ISSUE THREAD

**Issue by yubathom** [SPURB/outorga-backend#13]
Na endpoint `/fila` o query filter do parâmetro `IdGeo` não está funcionado.  

**exemplo**:
a endpoint abaixo retorna toda a fila
https://servicos.spurbanismo.sp.gov.br/cepacs/api/fila?IdGeo=742

O resultado esperado seria um array com um ou mais itens de fila, neste caso um array com um item, ou 404, mas nunca todos os itens de `/fila`

**Comment by hsolucas** [comment]
Atualizado com o filtro funcionando, favor validar.

https://servicos.spurbanismo.sp.gov.br/cepacs/api/fila?IdGeo=742

**Comment by yubathom** [comment]
@m-dantas
