### ISSUE TITLE
Overfetching em `/sqls`

### ISSUE THREAD

**Issue by yubathom** [SPURB/outorga-backend#2]
Remover o objeto `FilaCepac` das enpoints `sqls` manter apenas `IdFilaCepac`.

**Comment by yubathom** [comment]
@hsolucas, a api pública ainda está retornando o objeto FilaCepac na endpoint `sqls`.

Para reproduzir: 
1. Acessar
https://spurb.github.io/outorga-backend/#setor-quadras-e-lotes

2. Clicar em testar /sqls  (ver resposta no painel direito)

**Comment by hsolucas** [comment]
Resolvido.
