### ISSUE TITLE
feat(api): cadastro de alterações de status de item de fila

### ISSUE THREAD

**Issue by yubathom** [SPURB/outorga-backend#8]
Foi levantado na reunião com a DGO a necessidade de registrar alterações no `Status` de cadastro, ter um histórico das alterações. Desta forma seria necessário criar uma tabela com a seguinte estrutura:
| id  | IdCadastro | IdStatus | Data de alteração |
|-----|------------|----------|---------------|
| _Int_ | _FkInt_      | _FkInt_    | _Datetime_      |

A dúvida que eu tenho é como fazer esse registro. Acho que seriam duas opções: 
 1. Criar o registro direto no backend observando alterações na coluna de IdStatus da tabela _Fila_ (ou fazer esta verificação e registro no PUT de um item da fila)
 2. Criar as endpoints desta tabela e deixar para o frontend a responsabilidade de criar estes registros

Qual abordagem acha melhor @hsolucas ?

**Comment by hsolucas** [comment]
Será criada uma trigger no banco para cada atualização de registro na tabela fila cepac

**Comment by hsolucas** [comment]
Tabela de histórico criada.
Trigger criada, será acionada sempre que concluído um UPDATE na tabela fila cepac.

![image](https://user-images.githubusercontent.com/5081298/90298745-c0744880-de69-11ea-8b1f-a6c0ed260205.png)
